spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EBank loans related QA APIs "
  contactDetails:
    name: "Gurav B - QA Lead"
    email: "gaurav@gmail.com"
  onCallSupport:
    - (+91) 97668876867
    - (853) 546-3467