spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EBank loans related prod APIs "
  contactDetails:
    name: "Sumeet P - Product Owner"
    email: "sumeet@gmail.com"
  onCallSupport:
    - (+91) 9850258989
    - (156) 342-0956