spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Gaurav B - QA Lead"
    email: "gaurav@gmail.com"
  onCallSupport:
    - (+91) 9766797171
    - (201) 236-1267