
build:
  version: "3.0"

loans:
  message: "Welcome to EBank loans related local APIs "
  contactDetails:
    name: "Mayur Badhe - Developer"
    email: "mayur@gmail.com"
  onCallSupport:
    - (+91) 9145587142
    - (546) 764-8934