spring:
  application:
    name: "configserver"
  profiles:
   # active: native
    active: git
  cloud:
    config:
      server:
       # native:
         # search-locations: "classpath:/config"
         # search-locations: "file:///D://Mayur//Udemy//EasyBytes//External_Configuration//"
        git:
          uri: "https://github.com/mayurbadhe36/ebank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1Ef61DF9AD8d3E5BB397F9"

server:
  port: 8071